apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - kind-redis.yaml

namespace: ms-boilerplate-go-dev

images:
  - name: 650155821999.dkr.ecr.sa-east-1.amazonaws.com/ms-boilerplate-go
    newName: ms-boilerplate-go # Imagem local
    newTag: dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ms-boilerplate-go
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ms-boilerplate-go
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: ms-boilerplate-go
