apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-boilerplate-go-sa
  labels:
    app: ms-boilerplate-go
  annotations:
    # IRSA: eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/ms-boilerplate-go-role
automountServiceAccountToken: false
