apiVersion: v1
kind: ServiceAccount
metadata:
  name: people-service-registry-sa
  labels:
    app: people-service-registry
  annotations:
    # IRSA: eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/people-service-registry-role
automountServiceAccountToken: false
