apiVersion: v1
kind: Secret
metadata:
  name: ms-boilerplate-go-secrets
  labels:
    app: ms-boilerplate-go
type: Opaque
stringData:
  # Em dev local, usamos secrets inline (NÃO fazer isso em prod!)
  DB_PASSWORD: "password"
